version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependency
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependency
