sauce_connect: true
loopback: airtap.local
providers:
  - airtap-sauce
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: iphone
    version: latest
  - name: microsoftedge
    version: latest
  - name: android
    version: latest
